### ISSUE TITLE
README

### ISSUE THREAD

**Issue by camilacarvalho** [MisaelAugusto/recycle-it#1]
Vi que estéticamente seu README está muito bom, tem bastante cores, informações, mas acho que a principal informação faltou. Acredito que inicialmente, e sugerindo logo após a logo deveria ter uma introdução sobre o que é o seu projeto. Saí clicando nos links esperando me deparar com essa informação em algum momento mas não encontrei. Mesmo que estejam em alguma parte, acho que essa informação deveria ser a primeira, antes de qualquer outra por ser prioridade para entender todo o resto.

**Comment by MisaelAugusto** [comment]
Eu só faço uma descrição do projeto dentro dos arquivos README.pt.md e README.en.md, dá para acessar clicando no nome do idioma que deseja ler no readme de entrada do repositório, o README.md. Aí dá para escolher entre a versão em português e em inglês. Mas confesso que também considero essa abordagem menos fluída. 😅 Além disso, o link que leva para os requisitos originalmente eu não coloco no readme de entrada do repositório, coloquei apenas para correção da entrega do layout, acredito que sem ele fica menos poluído de links. Obrigado pelo feedback, vou tentar melhorar isso ! 😄
