### ISSUE TITLE
Componentes

### ISSUE THREAD

**Issue by AramisAraujo** [MisaelAugusto/recycle-it#2]
Notei que há alguns componentes que talvez sejam muito atômicos como 'Input' e 'Button', estão sempre contidos num componente 'container'. Pode haver algum motivo para isto no futuro, mas acredito que seria legal avaliar se é necessário fazer esses componentes tão básicos.

**Comment by MisaelAugusto** [comment]
Esses componentes ainda vão receber mais propriedades e posteriormente pretendo adicionar uma biblioteca para tratar de formulários, então preciso manter componentes de input isolados.

Obrigado pelo feedback ! 😄️
