### ISSUE TITLE
Tornar o Readme mais acessível a pessoa que visita o site.

### ISSUE THREAD

**Issue by matheusgr** [MisaelAugusto/recycle-it#4]
O Readme tá legal do ponto de vista de desenvolvimento / processo, mas seria legal torná-lo amigável ao usuário para ter uma ideia geral do que é o projeto. Descrever as páginas principais é um jeito mais direto a isso e pode facilitar a aceitação do projeto.

**Comment by MisaelAugusto** [comment]
Um preview no formato .gif das telas desenvolvidas até o momento ou imagens do layout podem resolver isso ?

**Comment by matheusgr** [comment]
sim. só atualiza de acordo com a implementação de novas funcionalidades e talvez a descrição em 1 linha da tela.
